routes/web.php
<?php

use App\Models\Piece;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $all_sections=\App\Models\Main_section::all();
    $roles=\Spatie\Permission\Models\Role::all();

    return view('new_template.index',['all_sections'=>$all_sections,'roles'=>$roles]);

});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    $now = Carbon::now();
    $date = Carbon::parse($now)->toDateTimeString();
    $pieces=Piece::all();
    $id=-1;
    foreach ($pieces as $piece){
        if($piece->exp_date >=$date && $piece->start_date <=$date){
            $id=$piece->id;
        }
    }
    $all_sections=\App\Models\Main_section::all();

    $pieces=\App\Models\Piece::all()->whereNotIn('id',$id);
        $roles=\Spatie\Permission\Models\Role::all();

    return view('new_template.index',['pieces'=>$pieces,'all_sections'=>$all_sections,'roles'=>$roles]);
});
    Route::resource('users', UserController::class);

Route::group(['middleware' => ['auth']], function() {


    Route::resource('roles', RoleController::class);



Route::get('/index', function () {
    $all_sections=\App\Models\Main_section::all();
        $roles=\Spatie\Permission\Models\Role::all();

    return view('new_template.index',['all_sections'=>$all_sections,'roles'=>$roles]);
});





Route::get('/get_piece/{piece}', 'App\Http\Controllers\HomeController@get_piece');



Route::get('/add/{id}', 'App\Http\Controllers\HomeController@add');
Route::post('/add_from_bride/{id}', 'App\Http\Controllers\PieceController@update_from_bride')->name('add_from_bride');

Route::get('/block/{id}', 'App\Http\Controllers\UserController@block')->name('block');
Route::get('/unblock/{id}', 'App\Http\Controllers\UserController@unblock')->name('unblock');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
     use Notifiable;
    use TwoFactorAuthenticatable;
use HasRoles;
    protected $connection="mysql";
    public function bid()
    {
        return $this->hasMany(Bid:: Class,'user_id');
    }
    public function piece()
    {
        return $this->hasMany(Piece:: Class,'winner_id');
    }
    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
       protected $fillable = [
        'name', 'email', 'password', 'mobile_number',
        'username','profile_photo_path','remember_token','type','device_token','status'


    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
         'mobile_number',
        'username',

           ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
      protected $appends = [
        'profile_photo_path',
    ];
    public function getImagePathAttribute()
    {
        if ($this->profile_photo_path) {
           return Storage::url('upload/'.$this->profile_photo_path);
        }
        return asset('images/default.png');
    }

       public function appointments()
    {
        return $this->hasMany(Appointment::Class);
    }

}

app/Http/Controllers/UserController.php
<?php   
namespace App\Http\Controllers;
    
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\Models\Role;
use App\Models\Main_section;
use Spatie\Permission\Models\Permission;
use DB;
use Hash;
use Illuminate\Support\Arr;
    
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
      function __construct()
    {
         $this->middleware('permission:إدارة المستخدمين ', ['only' => ['create','edit','update']]);
     
    }
    public function display()
    {
        $user=User::all();
        $roles=Role::all();
        return view('new_template.control_users',['user'=>$user,'roles'=>$roles]);
    }
     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
        public function index(Request $request)
    {
        $data = User::orderBy('id','DESC')->paginate(5);
        return view('users.index',compact('data'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }
     public function block($id)
    {
        $user = User::find($id);
        $user->status=0;
        $user->save();
        return back();
    }
       public function unblock($id)
    {
        $user = User::find($id);
        $user->status=1;
        $user->save();
        return back();
    }
     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function create()
    {
         
         $data = User::orderBy('id','DESC')->paginate(5);
        $all_sections=Main_section::all();
         $roles=\Spatie\Permission\Models\Role::all();

        return view('users.add_user',['all_sections'=>$all_sections,'data'=>$data,'roles'=>$roles]);
    }

     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
                   ]);
      
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
        $request->type='user';
        $input['type'] =$request->type;
         $request->image_path='images/33.png';
       $input['image_path'] =$request->image_path;

        $role = Role::find(1);
         $permissions = Permission::pluck('id','id')->all();
        

        $user = User::create($input);
        $user->assignRole([$role->id]);
        Auth::loginUsingId($user->id);

      
        return redirect('/dashboard');    }

     /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('users.show',compact('user'));
    }

     /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $user = User::find($id);
        $roles = Role::all();
        $userRoles = DB::Connection('mysql2')->table("model_has_roles")->where("model_has_roles.model_id",$id)
            ->pluck('model_has_roles.role_id','model_has_roles.role_id')
            ->all();
        $all_sections=\App\Models\Main_section::all();
    
        return view('new_template.edit_user',compact('user','roles','userRoles','all_sections'));
    }

     /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
    

        $input = $request->all();
       
    
        $user = User::find($id);
        $user->update($input);
        DB::Connection('mysql2')->table('model_has_roles')->where('model_id',$id)->delete();
    
        $user->assignRole($request->input('roles'));
    
        return redirect()->route('control_users');
    }

     /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('users.index')
                        ->with('success','User deleted successfully');
    }
}

resources/views/users/add_user.blade.php
@extends('master1')
@section('contents')
      <!-- ======= Why Us Section ======= -->
      <section id="why-us" class="why-us section-bg"style="margin-top:30px">
         <div class="container-fluid" data-aos="fade-up">
            <div class="row ">
               <div class="col-lg-7 d-flex flex-column justify-content-center align-items-stretch  order-2 order-lg-1">
                  <section id="contact" class="contact">
                     <div  class="container"  >
               <form method="POST" action="{{ route('users.store') }}" enctype="multipart/form-data" >
                         @csrf
                           <div class="row d-flex justify-content-center align-items-center">
                              <header class="section-header">
                                 <h3> إنشاء حساب</h3>
                              </header>
                              <div class="form-group col-md-8" style="margin-top: 15px;">
                                 <div class="form-outline mb-4" >
                                    {!! Form::text('name', null, array('placeholder' => 'الاسم','class' => 'form-control mx-sm-3')) !!}
                                 </div>
                                 <div class="form-outline mb-4">
                                     {!! Form::text('email', null, array('placeholder' => 'الإيميل ','class' => 'form-control mx-sm-3')) !!}
                                 </div>
                                 <div class="form-outline mb-4">
                                    {!! Form::password('password', array('placeholder' => 'كلمة المرور ','class' => 'form-control mx-sm-3')) !!}
                                 </div>
                                  <div class="form-outline mb-4">
                                    {!! Form::password('confirm-password', array('placeholder' => 'تأكيد كلمة المرور ','class' => 'form-control mx-sm-3')) !!}
                                 </div>
                                      <div class="form-group" style="width: 220px;" >
           
      </div>
                              </div>
                           </div>
                           <div class="text-center"><button type="submit">إنشاء </button></div>

                           <h6 class="title text-center" style="padding:10px;"><a href="/login">تسجيل الدخول </a></h6>
                        </form>
                     </div>
                  </section>
               </div>
               <div class="col-lg-5 align-items-stretch order-1 order-lg-2 img" style='background-image: url("assets/img/register2.png");' data-aos="zoom-in" data-aos-delay="150">&nbsp;</div>
            </div>
         </div>
      </section>
   @endsection