routes/web.php
<?php

use App\Models\Piece;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $all_sections=\App\Models\Main_section::all();
    $roles=\Spatie\Permission\Models\Role::all();

    return view('new_template.index',['all_sections'=>$all_sections,'roles'=>$roles]);

});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    $now = Carbon::now();
    $date = Carbon::parse($now)->toDateTimeString();
    $pieces=Piece::all();
    $id=-1;
    foreach ($pieces as $piece){
        if($piece->exp_date >=$date && $piece->start_date <=$date){
            $id=$piece->id;
        }
    }
    $all_sections=\App\Models\Main_section::all();

    $pieces=\App\Models\Piece::all()->whereNotIn('id',$id);
        $roles=\Spatie\Permission\Models\Role::all();

    return view('new_template.index',['pieces'=>$pieces,'all_sections'=>$all_sections,'roles'=>$roles]);
});
    Route::resource('users', UserController::class);

Route::group(['middleware' => ['auth']], function() {


    Route::resource('roles', RoleController::class);



Route::get('/index', function () {
    $all_sections=\App\Models\Main_section::all();
        $roles=\Spatie\Permission\Models\Role::all();

    return view('new_template.index',['all_sections'=>$all_sections,'roles'=>$roles]);
});





Route::get('/get_piece/{piece}', 'App\Http\Controllers\HomeController@get_piece');



Route::get('/add/{id}', 'App\Http\Controllers\HomeController@add');
Route::post('/add_from_bride/{id}', 'App\Http\Controllers\PieceController@update_from_bride')->name('add_from_bride');

Route::get('/block/{id}', 'App\Http\Controllers\UserController@block')->name('block');
Route::get('/unblock/{id}', 'App\Http\Controllers\UserController@unblock')->name('unblock');
});

resources/views/new_template/actions.blade.php
@extends('master') @section('contents')
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center" style="font-family: font-family: 'Droid Arabic Kufi', serif;">
   <div class="container">
      <div class="row">
         <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
            <h1> مزادات مغرية  من أجلك </h1>
            <h2>نحن نعمل باستمرار على جلب العروض الجديدة ، لذا استمر في زيارة موقعنا على الويب حتى لا تفوتك الفرصة التالية.</h2>

         </div>
         <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
            <img src="assets/img/banner-2.png" class="img-fluid animated" alt="">
         </div>
      </div>
   </div>
   </section><!-- End Hero -->
   <!-- ======= Portfolio Section ======= -->

   <section id="pricing" class="pricing" style="font-family: 'Droid Arabic Kufi', serif;">
      <div class="container" data-aos="fade-up">



      <!-- start size filter -->


      <!-- end filter -->

         <div class="section-title">
            <h2>المزادات</h2>
            <p>نرحب بك للحضور والانضمام إلى الحدث في أي من مزاداتنا القادمة..</p>
         </div>






         <ul class="nav nav-pills mb-3 d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100"role="tablist">
            <li class="nav-item" role="presentation">
               <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">المزادات الحالية</button>
            </li>
            <li class="nav-item" role="presentation">
               <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false"> المزادات القادمة</button>
            </li>
         </ul>
         <div class="row tab-content" data-aos="fade-up" data-aos-delay="200">
            <!-- start live bidding -->
            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
               <div class="row">
                   @if($current_piece !=null)
                  <div class="col-lg-3" data-aos="fade-up" data-aos-delay="100" >
                     <div class="box">
                        <div class="portfolio-img"> <!--start slide image -->
                        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                           <div class="carousel-indicators">
                              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                           </div>
                           <div class="carousel-inner">
                              <div class="carousel-item active portfolio-img">
                                 <img  src="{{$current_piece->images[0]->piece_img}}" class="card-img-top  " alt="...">
                              </div>


                           </div>
                           <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                           <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                           <span class="visually-hidden">Previous</span>
                           </button>
                           <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                           <span class="carousel-control-next-icon" aria-hidden="true"></span>
                           <span class="visually-hidden">Next</span>
                           </button>
                        </div>
                        <!--end slide image --></div>

                        <ul class="list-group list-group-flush task-list">



                           <li >
                              <div class="col-lg-12">
                                 <div class="member d-flex align-items-start" data-aos="zoom-in" data-aos-delay="100">
                                    <div class="pic">   <img src="assets/img/desc2.jpg" class="rounded-circle" alt=""  style="width: 50px; margin: 10px;">
                                    </div>
                                    <div class="member-info" >
                                       <h4 >الوصف</h4>
                                       <!--  <span>فستان نهدي</span> -->
                                       <p>{{$current_piece->discription}}</p>

                                    </div>
                                 </div>
                              </div>
                           </li>

                        </ul>
                         @auth

                        @hasanyrole($roles)
                         <div class="text-center">
                           <a href="{{route('bid.index')}}" class=" buy-btn" style="margin-bottom: 10px;">عرض المزايدة</a>
                        </div>
                        @else
                        <div class="text-center">
                           <a href="{{route('bid.index')}}" class=" buy-btn" style="margin-bottom: 10px;">المشاركة الآن</a>
                        </div>
                        @endhasanyrole
                        @endauth
                     </div>

                  </div>

               </div>
                @endif
            </div>
            <!-- end live bidding -->
            <!-- start next bidding -->
            <div class="tab-pane fade " id="pills-contact" role="tabpanel" aria-labelledby="pills-home-tab">

               <div class="row" >
                   @foreach($futur_piece as $futur_piece)
                  <div class="col-lg-3" data-aos="fade-up" data-aos-delay="100" >
                     <div class="box">
                        <div class="portfolio-img"> <!--start slide image -->
                        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                           <div class="carousel-indicators">
                              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                           </div>
                           <div class="carousel-inner">
                              <div class="carousel-item active portfolio-img">
                                 <img  src="{{$futur_piece->images[0]->piece_img}}" class="card-img-top  " alt="...">
                              </div>
                              <div class="carousel-item portfolio-img">
                                 <img  src="{{$futur_piece->images[0]->piece_img}}" class="card-img-top  " alt="...">
                              </div>
                              <div class="carousel-item portfolio-img">
                                 <img  src="{{$futur_piece->images[0]->piece_img}}" class="card-img-top  " alt="...">
                              </div>
                           </div>
                           <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                           <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                           <span class="visually-hidden">Previous</span>
                           </button>
                           <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                           <span class="carousel-control-next-icon" aria-hidden="true"></span>
                           <span class="visually-hidden">Next</span>
                           </button>
                        </div>
                        <!--end slide image --></div>

                        <ul class="list-group list-group-flush task-list">



                           <li >
                              <div class="col-lg-12">
                                 <div class="member d-flex align-items-start" data-aos="zoom-in" data-aos-delay="100">
                                    <div class="pic">   <img src="assets/img/desc2.jpg" class="rounded-circle" alt=""  style="width: 50px; margin: 10px;">
                                    </div>
                                    <div class="member-info" >
                                       <h4 >الوصف</h4>
                                       <!--  <span>فستان نهدي</span> -->
                                       <p>{{$futur_piece->discription}}</p>

                                    </div>
                                 </div>
                              </div>
                           </li>
                           <li >
                              <div class="col-lg-12">
                                 <div class="member d-flex align-items-start" data-aos="zoom-in" data-aos-delay="100">
                                    <div class="pic">   <img src="assets/img/start.jpg" class="rounded-circle" alt=""  style="width: 50px; margin: 10px;">
                                    </div>
                                    <div class="member-info">
                                       <h4  > تاريخ البدء</h4>
                                       <!--  <span>فستان نهدي</span> -->
                                       <h4 style="color: #444444;font-size: 20px;">{{$futur_piece->start_date}}</h4 >

                                    </div>
                                 </div>
                              </div>
                           </li>
                           <li >
                              <div class="col-lg-12">
                                 <div class="member d-flex align-items-start" data-aos="zoom-in" data-aos-delay="100">
                                    <div class="pic">   <img src="assets/img/end.jpg" class="rounded-circle" alt=""  style="width: 50px; margin: 10px;">
                                    </div>
                                    <div class="member-info">
                                       <h4  >تاريخ الإنتهاء</h4>
                                       <!--  <span>فستان نهدي</span> -->
                                       <h4 style="color: #444444;font-size: 20px;">{{$futur_piece->exp_date}}</h4 >

                                    </div>
                                 </div>
                              </div>
                           </li>
                        </ul>

                     </div>
                  </div>
                   @endforeach
               </div>

            </div>

         </div>
         <!-- end next bidding -->
      </div>

</section>
<!-- End Portfolio Section -->
@endsection

resources/views/new_template/add_from_bride.blade.php
@extends('master')
@section('contents')
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
        <h1> مزادات مغرية  من أجلك </h1>
        <h2>نحن نعمل باستمرار على جلب العروض الجديدة ، لذا استمر في زيارة موقعنا على الويب حتى لا تفوتك الفرصة التالية.</h2>
        
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
        <img src="/assets/img/dashboard.png" class="img-fluid animated" alt="">
      </div>
    </div>
  </div>
</section>
<div class="row justify-content-center">
  <div class="col-lg-9 d-flex flex-column justify-content-center align-items-stretch  order-2 order-lg-1">
    <section id="contact" class="contact">
      <div  class="container"  >
        <!--  role="form" class="php-email-form" -->
        <form  method="POST" action="{{ route('add_from_bride',$piece_bride_id) }}" enctype="multipart/form-data" class="display">
          @csrf
          <div class="row d-flex  align-items-center">
            
            <div class="form-group ">
              <select name="sub_section_id" class="form-control" >
                @foreach(\App\Models\Main_section::find(5)->sub_sections as $sub_s)
                <option value="{{$sub_s->id}}">{{$sub_s->name}}</option>
                @endforeach
              </select>
            </div>
             <div class="form-group col-md-6">
                <input type="text" name="discription" class="form-control" id="name" value="{{$des}}" placeholder ="" style="margin-top: 15px;" >

              </div>
              
                 <div class="form-group col-md-6">
                  <input type="number" name="bidding_price" class="form-control" id="name" placeholder ="السعر الإبتدائي" required style="margin-top: 15px;">
                </div>
                
                <div class="form-group col-md-6">
                  <input type="number" name="added_value" class="form-control" id="name" required placeholder="قيمة المزايدة" style="margin-top: 15px;">
                </div>
                <div class="form-group col-md-6">
                  <input type="text" name="start_date" input type="text" class="form-control" onfocus="(this.type='datetime-local')" onblur="if(!this.value)this.type='text'" placeholder="تاريخ البدء" required style="margin-top: 15px;">
                </div>
                <div class="form-group col-md-6">
                  <input type="text" input type="text" class="form-control" onfocus="(this.type='datetime-local')" onblur="if(!this.value)this.type='text'" name="exp_date" id="email" required placeholder="تاريخ الإنتهاء" required style="margin-top: 15px;">
                </div>
                
              </div>
              
              
              <div class="text-center"><button type="submit" style="margin-top: 15px;">حفظ</button></div>
              @if ($errors!=null)
              <div class="alert alert-danger">
                <ul>
                  <li>
                    {{ $errors }}
                  </li>
                </ul>
              </div><br />
              @endif
            </form>
          </div>
        </section>
      </div>
      
    </div>
    @endsection

resources/views/new_template/control_users.blade.php
@extends('master')
@section('contents')
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
        <h1> مزادات مغرية  من أجلك </h1>
        <h2>نحن نعمل باستمرار على جلب العروض الجديدة ، لذا استمر في زيارة موقعنا على الويب حتى لا تفوتك الفرصة التالية.</h2>
        <!-- <div class="d-flex justify-content-center justify-content-lg-start">
          <a href="#about" class="btn-get-started scrollto">Get Started</a>
          <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>
        </div> -->
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
        <img src="assets/img/usercontrol.png" class="img-fluid animated" alt="">
      </div>
    </div>
  </div>
</section>
<!-- End Hero -->
<section id="contact" class="contact">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>إدارة  المستخدمين</h2>
      
    </div>
    <div class="row mt justify-content-center">
      <div class="col-lg-8 " data-aos="fade-up" data-aos-delay="200">
        <div class="content-panel">
          <table class="table table-striped table-advance table-hover">
            
            <hr>
            <thead>
              <tr>
                <th class="text-center"><i class="bi bi-person-fill" ></i> المستخدمين </th>
                
                <th class="text-center">البريد الإلكتروني </th>
                <th class="text-center">تعديل صلاحية</th>
                <th class="text-center"><i class=" bi bi-slash-circle" style="color: red;"></i> Block </th>
               
                
              </tr>
            </thead>
            <tbody>
              
              
              @foreach ($data as $key => $user)
             <?php

$userRoles = DB::Connection('mysql2')->table("model_has_roles")->where("model_has_roles.model_id",$user->id)
            ->pluck('model_has_roles.role_id','model_has_roles.role_id')
            ->all();
?>
@if(!$userRoles)
              <tr>
                <td class="text-center">
                  
                  <h6 style=" color: #37517e;">{{$user->name}}</h6>
                  
                </td>
                
                
                <td class="text-center">
                  {{$user->email}}
                </td>
                
               <!--  <td class="text-center">
                  @if(!empty($user->getRoleNames()))
                  @foreach($user->getRoleNames() as $v)
                  <h6 style=" color: #37517e;">{{ $v }}</h6>
                  @endforeach
                  
                  @else
                  <h6 style=" color: #37517e;">لا يوجد </h6>
                  @endif
                </td> -->
                
                <td class="text-center">
                  <a  class="btn btn-primary btn-xs"  href="{{ route('users.edit', $user->id) }}">
                    <i class=" bi bi-pencil  btn-xs"></i>
                  </a>
                  
                  
                </td>
                <td class="text-center">
                  @if($user->status==1)
                  <a class="btn btn-success btn-xs"  href="{{ route('block', $user->id) }}">
                    <i class=" bi bi-slash-circle  btn-xs"></i>
                  </a>
                  @else
                  <a class="btn btn-danger btn-xs"  href="{{ route('unblock', $user->id) }}">
                    <i class=" bi bi-slash-circle  btn-xs"></i>
                  </a>
                  @endif
                </td>
                
              </tr>
              @endif
              @endforeach
              
              
            </tbody>
          </table>
        </div>
        <!-- /content-panel -->
      </div>
      <!-- /col-md-12 -->
    </div>
  </div>
</section>
@endsection

resources/views/new_template/control_users_role.blade.php
@extends('master')
@section('contents')
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
        <h1> مزادات مغرية  من أجلك </h1>
        <h2>نحن نعمل باستمرار على جلب العروض الجديدة ، لذا استمر في زيارة موقعنا على الويب حتى لا تفوتك الفرصة التالية.</h2>
        <!-- <div class="d-flex justify-content-center justify-content-lg-start">
          <a href="#about" class="btn-get-started scrollto">Get Started</a>
          <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>
        </div> -->
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
        <img src="assets/img/usercontrol.png" class="img-fluid animated" alt="">
      </div>
    </div>
  </div>
</section>
<!-- End Hero -->
<section id="contact" class="contact">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>إدارة  المستخدمين</h2>
      
    </div>
    <div class="row mt justify-content-center">
      <div class="col-lg-8 " data-aos="fade-up" data-aos-delay="200">
        <div class="content-panel">
          <table class="table table-striped table-advance table-hover">
            
            <hr>
            <thead>
              <tr>
                <th class="text-center"><i class="bi bi-person-fill" ></i> المستخدمين </th>
                
                <th class="text-center">البريد الإلكتروني </th>
                <th class="text-center">الصلاحية</th>
                <th class="text-center">تعديل صلاحية</th>
                <th class="text-center"><i class=" bi bi-slash-circle" style="color: red;"></i> Block </th>
               
                
              </tr>
            </thead>
            <tbody>
              
              
              @foreach ($data as $key => $user)
<?php

$userRoles = DB::Connection('mysql2')->table("model_has_roles")->where("model_has_roles.model_id",$user->id)
            ->pluck('model_has_roles.role_id','model_has_roles.role_id')
            ->all();
?>
@if($userRoles)
              <tr>
                <td class="text-center">
                  
                  <h6 style=" color: #37517e;">{{$user->name}}</h6>
                  
                </td>
                
                
                <td class="text-center">
                  {{$user->email}}
                </td>
                
                <td class="text-center">
                  @if(!empty($user->getRoleNames()))
                  @foreach($user->getRoleNames() as $v)
                  <h6 style=" color: #37517e;">{{ $v }}</h6>
                  @endforeach
                  
                  @else
                  <h6 style=" color: #37517e;">لا يوجد </h6>
                  @endif
                </td>
                
                <td class="text-center">
                  <a  class="btn btn-primary btn-xs"  href="{{ route('users.edit', $user->id) }}">
                    <i class=" bi bi-pencil  btn-xs"></i>
                  </a>
                  
                  
                </td>
                <td class="text-center">
                  @if($user->status==1)
                  <a class="btn btn-success btn-xs"  href="{{ route('block', $user->id) }}">
                    <i class=" bi bi-slash-circle  btn-xs"></i>
                  </a>
                  @else
                  <a class="btn btn-danger btn-xs"  href="{{ route('unblock', $user->id) }}">
                    <i class=" bi bi-slash-circle  btn-xs"></i>
                  </a>
                  @endif
                </td>
                
              </tr>
              @endif
              @endforeach
              
              
            </tbody>
          </table>
        </div>
        <!-- /content-panel -->
      </div>
      <!-- /col-md-12 -->
    </div>
  </div>
</section>
@endsection

resources/views/new_template/display_role.blade.php
@extends('master')
@section('contents')
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
        <h1> مزادات مغرية  من أجلك </h1>
        <h2>نحن نعمل باستمرار على جلب العروض الجديدة ، لذا استمر في زيارة موقعنا على الويب حتى لا تفوتك الفرصة التالية.</h2>
        <!-- <div class="d-flex justify-content-center justify-content-lg-start">
          <a href="#about" class="btn-get-started scrollto">Get Started</a>
          <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>
        </div> -->
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
        <img src="/assets/img/usercontrol.png" class="img-fluid animated" alt="">
      </div>
    </div>
  </div>
</section>
<!-- End Hero -->
<section id="contact" class="contact">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>إدارة الصلاحيات</h2>
      
    </div>
   <div class="row mt justify-content-center">
          <div class="col-lg-8 " data-aos="fade-up" data-aos-delay="200">
            <div class="content-panel">
              <table class="table table-striped table-advance table-hover">
               
                <hr>
                <thead>
                  <tr>
                    <th class="text-center"><i class="bi bi-person-fill" ></i>الصلاحيات</th>
                    <th class="text-center"></i>العمليات</th>
                   
                    
                  </tr>
                </thead>
                <tbody>
                       @foreach ($roles as $key => $role)
                  <tr>
                    <td class="text-center">
                      <h6 style=" color: #37517e;">{{ $role->name }}</h6>
                    </td>
                    <td class="text-center">
                           <form action="{{ route('roles.destroy',$role->id) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger btn-xs " class="button"
                                        method="post" href="{{ route('roles.destroy',$role->id) }}" style="margin-right:-5px; ">
                                        <i class="bi bi-trash"></i>
                                        </button>
                                      </form>
                                <button class=" btn-success btn-xs dashbtn">
                                  <i class=" bi bi-pencil"></i></button></a>
                    </td>
                   
                   
                  </tr>
                  @endforeach
                
                </tbody>
              </table>
            </div>
            <!-- /content-panel -->
          </div>
          <!-- /col-md-12 -->
        </div>
  </div>
</section>
@endsection

resources/views/new_template/edit_user.blade.php
@extends('master')
@section('contents')
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
        <h1> مزادات مغرية  من أجلك </h1>
        <h2>نحن نعمل باستمرار على جلب العروض الجديدة ، لذا استمر في زيارة موقعنا على الويب حتى لا تفوتك الفرصة التالية.</h2>
        <!-- <div class="d-flex justify-content-center justify-content-lg-start">
          <a href="#about" class="btn-get-started scrollto">Get Started</a>
          <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>
        </div> -->
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
        <img src="/assets/img/usercontrol.png" class="img-fluid animated" alt="">
      </div>
    </div>
  </div>
</section>
<!-- End Hero -->
<section id="contact" class="contact">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>تعديل المستخدم </h2>
      
    </div>
    <div class="row mt justify-content-center">
      <div class="col-lg-8 " data-aos="fade-up" data-aos-delay="200">
        <div class="content-panel">
        
               {!! Form::model($user, ['method' => 'PATCH','route' => ['users.update', $user->id],'class'=>'display']) !!}
            <div class="row">
              
             
                  <label>الصلاحيات :</label>
                 
               
              @foreach($roles as $role)
                  <div class="col-lg-3 col-md-3 col-3">
                <div class="text-center " style="  padding: 30px;">
                  
                   
                   {{ Form::checkbox('roles[]', 
                   $role['id'],
                    in_array($role['id'], $userRoles) ? true : false, array('class' => 'name')) }} 
                    {{ $role->name }}
                   </div>
              </div>
                    @endforeach
            </div>
            <div class="text-center">
              <button  class="close " type="submit">تعديل </button>
            </div>
           {!! Form::close() !!}
          <div>
            <!-- <label for="name">Assigned Permissions</label> -->
            
            
          </div>
        </div>
        <!-- /content-panel -->
      </div>
      <!-- /col-md-12 -->
    </div>
  </div>
</section>
@endsection