routes/web.php
<?php

use App\Models\Piece;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $all_sections=\App\Models\Main_section::all();
    $roles=\Spatie\Permission\Models\Role::all();

    return view('new_template.index',['all_sections'=>$all_sections,'roles'=>$roles]);

});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    $now = Carbon::now();
    $date = Carbon::parse($now)->toDateTimeString();
    $pieces=Piece::all();
    $id=-1;
    foreach ($pieces as $piece){
        if($piece->exp_date >=$date && $piece->start_date <=$date){
            $id=$piece->id;
        }
    }
    $all_sections=\App\Models\Main_section::all();

    $pieces=\App\Models\Piece::all()->whereNotIn('id',$id);
        $roles=\Spatie\Permission\Models\Role::all();

    return view('new_template.index',['pieces'=>$pieces,'all_sections'=>$all_sections,'roles'=>$roles]);
});
    Route::resource('users', UserController::class);

Route::group(['middleware' => ['auth']], function() {


    Route::resource('roles', RoleController::class);



Route::get('/index', function () {
    $all_sections=\App\Models\Main_section::all();
        $roles=\Spatie\Permission\Models\Role::all();

    return view('new_template.index',['all_sections'=>$all_sections,'roles'=>$roles]);
});





Route::get('/get_piece/{piece}', 'App\Http\Controllers\HomeController@get_piece');



Route::get('/add/{id}', 'App\Http\Controllers\HomeController@add');
Route::post('/add_from_bride/{id}', 'App\Http\Controllers\PieceController@update_from_bride')->name('add_from_bride');

Route::get('/block/{id}', 'App\Http\Controllers\UserController@block')->name('block');
Route::get('/unblock/{id}', 'App\Http\Controllers\UserController@unblock')->name('unblock');
});

app/Http/Controllers/RoleController.php
<?php
    
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use App\Models\User;
use Spatie\Permission\Models\Permission;
use Auth;
use DB;
    
class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    function __construct()
    {
        
         $this->middleware('permission:إدارة الصلاحيات', ['only' => ['destroy']]);
       
    }

     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::orderBy('id','DESC')->paginate(5);
        return view('roles.index',compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permission = Permission::get();
        $user=Auth::User();
         $all_sections=\App\Models\Main_section::all();
         $roles=Role::all();
        
         if(Auth::user()){ 
       return view('roles.add_roles',['user'=>$user,'all_sections'=>$all_sections,'permission'=>$permission,'roles'=>$roles]);}
       else return redirect('/login');
    }
 
     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);
    
        $role = Role::on('mysql2')->create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));
        // $user=Auth::User();
        // $user->syncPermissions($request->input('permission'));
    
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
            ->where("role_has_permissions.role_id",$id)
            ->get();
         $user=Auth::User();
        $all_sections=\App\Models\Main_section::all();
 $roles=\Spatie\Permission\Models\Role::all();
        return view('roles.show_roles',['role'=>$role,'roles'=>$roles,'rolePermissions'=>$rolePermissions,'user'=>$user,'all_sections'=>$all_sections]);
    }

     /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
         $user=Auth::User();
         $all_sections=\App\Models\Main_section::all();
        $rolePermissions = DB::Connection('mysql2')->table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();
     $roles=\Spatie\Permission\Models\Role::all();

        return view('roles.edit_role',['role'=>$role,'roles'=>$roles,'permission'=>$permission,'user'=>$user,'rolePermissions'=>$rolePermissions,'all_sections'=>$all_sections]);
    }

     /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);
    
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();
    
        $role->syncPermissions($request->input('permission'));
    
        return redirect('/roles/create');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::Connection('mysql2')->table("roles")->where('id',$id)->delete();
        return back();
    }
}

resources/views/roles/add_roles.blade.php
@extends('master')
@section('contents')
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
        <h1> مزادات مغرية  من أجلك </h1>
        <h2>نحن نعمل باستمرار على جلب العروض الجديدة ، لذا استمر في زيارة موقعنا على الويب حتى لا تفوتك الفرصة التالية.</h2>
        <!-- <div class="d-flex justify-content-center justify-content-lg-start">
          <a href="#about" class="btn-get-started scrollto">Get Started</a>
          <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>
        </div> -->
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
        <img src="/assets/img/dashboard.png" class="img-fluid animated" alt="">
      </div>
    </div>
  </div>
</section>
<!-- End Hero -->
<section id="contact" class="contact">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>إدارة  الصلاحيات</h2>
    </div>
    <ul class="nav nav-pills mb-3 d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100"role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">إضافة صلاحية </button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">عرض الصلاحيات</button>
      </li>
      
    </ul>
    <div class="row tab-content" data-aos="fade-up" data-aos-delay="200">
      <!-- add action -->
      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <div class="row">
          <div class="col-lg-12 mt-5 mt-lg-0 d-flex align-items-stretch">
            {!! Form::open(array('route' => 'roles.store','method'=>'POST','class'=>'display')) !!}
            <div class="row">
              
              <div class="form-group">
                {!! Form::text('name', null, array('placeholder' => 'الاسم ','class' => 'form-control')) !!}
              </div>
              
              @foreach($permission as $value)
              <div class="form-group col-lg-3 col-md-3" style="float: right;margin-top:30px;">
                
                {{Form::checkbox('permission[]',$value->id,false, array('class' => 'name'))}}{{$value->name}}
              </div>
              @endforeach
            </div>
            <div class="text-center" style="margin-top:60px;"><button type="submit">حفظ</button></div>
            
            {!! Form::close() !!}
          </div>
        </div>
      </div>
      
      
      <!-- all action -->
      <div class="tab-pane fade " id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
        <div class="row">
          <div class="col-lg-12 mt-5 mt-lg-0 d-flex align-items-stretch display">
            <table class="table table-striped table-advance table-hover ">
              
              <hr>
              <thead>
                <tr>
                  <th class="text-center"><i class="bi bi-person-fill" ></i>الصلاحية</th>
                  
                  <th class="text-center">الأذونات</th>
                  
                  <th></th>
                  
                </tr>
              </thead>
              <tbody>
                
                @foreach ($roles as $role)
                
                
                <?php
                $rolePermissions = Spatie\Permission\Models\Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
                ->where("role_has_permissions.role_id",$role->id)
                ->get();
                ?>
                
                <tr>
                  <td class="text-center">
                    
                    <h6 style=" color: #37517e;">{{$role->name}}</h6>
                    
                  </td>
                  
                  
                  
                  
                  <td class="text-center">
                    <p>
                      <a class="btn btn-primary btn-xs " data-toggle="collapse" href="#collapseExample{{$role->id}}" role="button" aria-expanded="false" aria-controls="collapseExample">
                        <i class=" bi bi-eye"></i>
                      </a>
                    </p>
                    
                    <div class="collapse" id="collapseExample{{$role->id}}">
                      @foreach ($rolePermissions as $rolePermission)
                      <div class="form-group col-lg-12 col-md-12" >
                        <ul class="task-list" >
                          
                          <a style="color: black;">{{$rolePermission['name']}}</a>
                          
                          
                        </ul>
                      </div>
                      @endforeach
                    </div>
                    
                  </td>
                  
                  <td class="text-center">
                    <a  class="btn btn-primary btn-xs"  href="{{ route('roles.edit', $role->id) }}">
                      <i class=" bi bi-pencil  btn-xs"></i>
                    </a>
                    
                    
                  </td>
                  
                </tr>
                
                
                @endforeach
                
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/roles/edit_role.blade.php
@extends('master')
@section('contents')
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
        <h1> مزادات مغرية  من أجلك </h1>
        <h2>نحن نعمل باستمرار على جلب العروض الجديدة ، لذا استمر في زيارة موقعنا على الويب حتى لا تفوتك الفرصة التالية.</h2>
        <!-- <div class="d-flex justify-content-center justify-content-lg-start">
          <a href="#about" class="btn-get-started scrollto">Get Started</a>
          <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>
        </div> -->
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
        <img src="/assets/img/dashboard.png" class="img-fluid animated" alt="">
      </div>
    </div>
  </div>
</section>
<!-- End Hero -->
<section id="contact" class="contact">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>تعديل الصلاحية </h2>

    </div>
    
    <div class="row tab-content" data-aos="fade-up" data-aos-delay="200">
    
     
   
     <!-- all action -->
   <div class="row">

          <div class="col-lg-12 mt-5 mt-lg-0 d-flex align-items-stretch ">
                {!! Form::model($role, ['method' => 'PATCH','route' => ['roles.update', $role->id],'class'=>'display']) !!}
                <div class="row">
                 
                <div class="form-group">
       
              
                <input type="text" list="piece" id="inputPassword6" class="form-control mx-sm-3" aria-describedby="passwordHelpInline"  name="name" value="{{$role->name}}" />
                                               
                </div>
               
                  @foreach($permission as $value)
                  <div class="form-group col-lg-3 col-md-3" style="float: right;margin-top:30px;">
                   
                   {{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }} {{ $value->name }}
                  </div>
                    @endforeach


              </div>


              <div class="text-center" style="margin-top:60px;"><button type="submit">حفظ</button></div>

                       
           {!! Form::close() !!}
          </div>
        </div>
       
       </div>
  </div>
</section>
@endsection